In [241]:
import pandas as pd

In [242]:
# Path to your Excel file
excel_path = "FKKD_2024.xlsx"  #

In [243]:
excel_file = pd.ExcelFile(excel_path, engine='openpyxl')
sheet_names = excel_file.sheet_names

In [244]:
print(sheet_names)

['2024_03', '2024_12', '2024_09', '2024_01', '2024_06', '2024_02', '2024_11', '2024_10', '2024_08', '2024_05', '2024_04']

In [245]:
# List to collect each sheet's data
all_data = []

In [246]:
for sheet in sheet_names:
    df = pd.read_excel(excel_path, sheet_name=sheet, engine='openpyxl')
    #df["Sheet"] = sheet  # Optional: track source sheet
    df["Hour"] = df["Hour"].astype(str).str.zfill(4)  # Ensure 4-digit strings
    df["Hour_int"] = df["Hour"].str[:2].astype(int)
    df["Minute"] = df["Hour"].str[-2:].astype(int)
    all_data.append(df)

In [247]:
# Merge all dataframes
weather_df = pd.concat(all_data, ignore_index=True)

In [248]:
weather_df.head()

,Year,Month,Day,Hour,Temp,DP,RH,Wind Speed,Visibility,Rain,Pressure,Hour_int,Minute
0,2024,3,31,2300,22,22,100.0,3,NaN,YES,1012,23,0
1,2024,3,31,2230,27,22,74.1,3,NaN,YES,1012,22,30
2,2024,3,31,2200,28,27,94.3,0,9999.0,YES,1011,22,0
3,2024,3,31,2130,28,27,94.3,3,9999.0,YES,1012,21,30
4,2024,3,31,2100,28,27,94.3,3,9999.0,YES,1011,21,0

In [249]:
weather_df.tail()

,Year,Month,Day,Hour,Temp,DP,RH,Wind Speed,Visibility,Rain,Pressure,Hour_int,Minute
8698,2024,4,1,0200,23,23,100.0,2,9999.0,YES,1010,2,0
8699,2024,4,1,0130,23,23,100.0,2,9999.0,YES,1010,1,30
8700,2024,4,1,0100,23,23,100.0,2,9999.0,YES,1010,1,0
8701,2024,4,1,0030,23,22,94.1,0,9999.0,YES,1011,0,30
8702,2024,4,1,0000,23,22,94.1,2,9999.0,YES,1012,0,0

In [250]:
weather_df["Datetime"] = pd.to_datetime(weather_df[["Year", "Month", "Day", "Hour_int", "Minute"]].rename(columns={"Hour_int": "Hour"}))

In [251]:
#weather_df["Datetime"] = pd.to_datetime(weather_df[["Year", "Month", "Day", "Hour"]])

In [252]:
# Sort by datetime if needed
weather_df = weather_df.sort_values(by="Datetime").reset_index(drop=True)

In [253]:
weather_df.head()

,Year,Month,Day,Hour,Temp,DP,RH,Wind Speed,Visibility,Rain,Pressure,Hour_int,Minute,Datetime
0,2024,1,1,0000,27,27,100.0,2,8000.0,NO,1011,0,0,2024-01-01 00:00:00
1,2024,1,1,0030,28,27,94.3,2,8000.0,NO,1011,0,30,2024-01-01 00:30:00
2,2024,1,1,0100,28,26,88.9,2,8000.0,YES,1011,1,0,2024-01-01 01:00:00
3,2024,1,1,0200,27,26,94.3,0,8000.0,YES,1010,2,0,2024-01-01 02:00:00
4,2024,1,1,0300,26,25,94.2,0,8000.0,NO,1010,3,0,2024-01-01 03:00:00

In [254]:
weather_df["Datetime"][:5]

0   2024-01-01 00:00:00
1   2024-01-01 00:30:00
2   2024-01-01 01:00:00
3   2024-01-01 02:00:00
4   2024-01-01 03:00:00
Name: Datetime, dtype: datetime64[ns]

In [255]:
weather_df["Datetime"][-5:]

8698   2024-12-31 01:00:00
8699   2024-12-31 02:00:00
8700   2024-12-31 03:00:00
8701   2024-12-31 04:00:00
8702   2024-12-31 08:00:00
Name: Datetime, dtype: datetime64[ns]

In [256]:
weather_df.to_csv("FKKD_2024_Processed.csv")