In [274]:
import pandas as pd

In [275]:
df = pd.read_csv("FKKD_2021_to_2024_processed.csv")

In [276]:
df.columns.to_list()

['Unnamed: 0',
 'Year',
 'Month',
 'Day',
 'Hour',
 'Temp',
 'DP',
 'RH',
 'Wind Speed',
 'Visibility',
 'Rain',
 'Pressure',
 'Hour_int',
 'Minute',
 'Datetime']

In [277]:
data = df[['Datetime', 'Temp','DP','RH', 'Wind Speed','Pressure','Visibility', 'Rain']]

In [278]:
data.head()

              Datetime Temp  DP     RH  Wind Speed  Pressure  Visibility Rain
0  2021-01-01 00:00:00   26  26  100.0           0    1010.0      7000.0   NO
1  2021-01-01 02:00:00   26  26  100.0           2    1009.0      2500.0   NO
2  2021-01-01 03:00:00   25  25  100.0           2       NaN      6000.0   NO
3  2021-01-01 04:00:00   25  25  100.0           0    1009.0      6000.0   NO
4  2021-01-01 05:00:00   25  25  100.0           0    1010.0      6000.0   NO

In [279]:
data.tail()

,Datetime,Temp,DP,RH,Wind Speed,Pressure,Visibility,Rain
23083,2024-12-31 01:00:00,27,26,94.3,0,1010.0,8000.0,NO
23084,2024-12-31 02:00:00,26,25,94.2,2,1009.0,9999.0,NO
23085,2024-12-31 03:00:00,26,25,94.2,1,1009.0,9999.0,NO
23086,2024-12-31 04:00:00,25,25,100.0,1,1009.0,9999.0,NO
23087,2024-12-31 08:00:00,29,25,79.0,2,1011.0,4000.0,NO

In [280]:
data.dtypes

Datetime       object
Temp           object
DP             object
RH            float64
Wind Speed      int64
Pressure      float64
Visibility    float64
Rain           object
dtype: object

In [281]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23088 entries, 0 to 23087
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Datetime    23088 non-null  object
 1   Temp        23085 non-null  object
 2   DP          23088 non-null  object
 3   RH          23088 non-null  float64
 4   Wind Speed  23088 non-null  int64
 5   Pressure    23081 non-null  float64
 6   Visibility  22862 non-null  float64
 7   Rain        23088 non-null  object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.4+ MB

In [282]:
print(data["Temp"].isnull().sum())

3

In [283]:
print(data["Temp"].unique())

['26' '25' '29' '30' '31' '33' '32' '28' '27' '34' '23' '24' '22' '35'
 '27.0' '26.0' '25.0' '29.0' '30.0' '31.0' '33.0' '32.0' '28.0' nan '24.0'
 '34.0' '35.0' '23.0' '22.0' 'Q1007' '21' '36' '37']

In [284]:
print(data["DP"].isnull().sum())

0

In [285]:
print(data.where(data["Temp"] == "Q1007")["Temp"].value_counts())

Temp
Q1007    1
Name: count, dtype: int64

In [286]:
print(data["DP"].unique())

['26' '25' '27' '24' '21' '23' '22' '28' '20' 'NO' '19' '29']

In [287]:
print(data.where(data["DP"] == "NO")["DP"].value_counts())

DP
NO    4
Name: count, dtype: int64

In [288]:
data["RH"].isnull().sum()

0

In [289]:
data["RH"].unique()

array([100. ,  79. ,  74.6,  74.8,  62.9,  70.6,  66.6,  66.8,  83.9,
        88.9,  94.3,  56. ,  79.2,  70.4,  59.2,  88.5,  94.1,  94.2,
        83.7,  88.8,  74.1,  88.7,  74.4,  70.3,  78.9,  59.5,  83.8,
        62.7,  83.6,  66.4,  88.6,  59. ,  55.8,  62.5,  52.7,  52.5,
        52.2,  84. ,  53. ,  70.1,  63.1,  89. ,  79.3,  70.8,  89.1,
        94.4,  78.6,  55.5,  69.9,  58.8,  62.2,  65.9,  55. ,  66.2,
        78.8,  46.7,  74.3,  59.7,  83.4,  49.6,  69.7,  74.9,  49.9,
        46.9,  56.2,  46.4,  41.2,  49.4,  84.1,  66.9,  78.5,  55.3,
        73.9,  83.3,  63.3,  56.5,  71. ,  47.2,  53.2,  59.9,  63.5,
        75.1,  79.4,  67.1,  56.7])

In [290]:
print(data["Wind Speed"].isnull().sum())

0

In [291]:
print(data["Wind Speed"].unique())

[ 0  2  3  4  5  1  7  6 10  8 11  9 14 13 18 12 17 15 16]

In [292]:
print(data["Pressure"].isnull().sum())

7

In [293]:
print(data["Pressure"].unique())

[1010. 1009.   nan 1011. 1008. 1007. 1012. 1006. 1013. 1005. 1004. 1014.
 1015. 1016. 1017. 1018.]

In [294]:
print(data["Visibility"].isnull().sum())

226

In [295]:
print(data["Visibility"].unique())

[7000. 2500. 6000. 1200. 1700. 4000. 8000. 9999. 1800. 1600. 4500. 2000.
 3400.   nan 3500. 4800. 2800. 5000. 9000. 1300. 3200. 3000. 2200. 3600.
 2300. 4200. 1400. 2400.  800. 3800. 1500.  700. 2900.  300. 1000. 2600.
  600.]

In [296]:
print(data["Rain"].isnull().sum())

0

In [297]:
print(data["Rain"].unique())

['NO' 'YES']

In [298]:
data.describe()

                 RH    Wind Speed      Pressure    Visibility
count  23088.000000  23088.000000  23081.000000  22862.000000
mean      87.467472      2.351048   1010.683376   8310.925072
std       12.412115      1.689013      2.214965   2401.205982
min       41.200000      0.000000   1004.000000    300.000000
25%       79.000000      1.000000   1009.000000   7000.000000
50%       94.100000      2.000000   1011.000000   9999.000000
75%      100.000000      3.000000   1012.000000   9999.000000
max      100.000000     18.000000   1018.000000   9999.000000

In [299]:
print(data.where(data["Temp"] == "Q1007")["Temp"].value_counts())

Temp
Q1007    1
Name: count, dtype: int64

## DROP RAW

In [300]:
print(len(data))

23088

In [301]:
data = data[data["Temp"].astype(str) != "Q1007"]

In [302]:
print(len(data))

23087

In [303]:
data = data[data["DP"].astype(str) != "NO"]

In [304]:
print(len(data))

23084

In [305]:
data.describe()

                 RH    Wind Speed      Pressure    Visibility
count  23084.000000  23084.000000  23080.000000  22858.000000
mean      87.467514      2.350806   1010.683536   8310.804576
std       12.412181      1.688946      2.214880   2401.362399
min       41.200000      0.000000   1004.000000    300.000000
25%       79.000000      1.000000   1009.000000   7000.000000
50%       94.100000      2.000000   1011.000000   9999.000000
75%      100.000000      3.000000   1012.000000   9999.000000
max      100.000000     18.000000   1018.000000   9999.000000

In [306]:
data["Visibility"] = pd.to_numeric(data["Visibility"], errors="coerce")
moving_avg = data["Visibility"].rolling(window=3, min_periods=1).mean()
data["Visibility"] = data["Visibility"].fillna(moving_avg)
data["Visibility"] = data["Visibility"].round(0).astype("Int64")

In [307]:
data["Visibility"].head()

0    7000
1    2500
2    6000
3    6000
4    6000
Name: Visibility, dtype: Int64

In [308]:
data["Pressure"] = pd.to_numeric(data["Pressure"])
moving_avg = data["Pressure"].rolling(window=3, min_periods=1).mean()
data["Pressure"] = data["Pressure"].fillna(moving_avg)
data["Pressure"] = data["Pressure"].round(0).astype("Int64")

In [309]:
data.describe()

                 RH    Wind Speed     Pressure   Visibility
count  23084.000000  23084.000000      23084.0      22992.0
mean      87.467514      2.350806  1010.684024  8315.623956
std       12.412181      1.688946     2.215478  2398.400169
min       41.200000      0.000000       1004.0        300.0
25%       79.000000      1.000000       1009.0       7000.0
50%       94.100000      2.000000       1011.0       9999.0
75%      100.000000      3.000000       1012.0       9999.0
max      100.000000     18.000000       1018.0       9999.0

In [310]:
data["Temp"] = pd.to_numeric(data["Temp"])
moving_avg = data["Temp"].rolling(window=3, min_periods=1).mean()
data["Temp"] = data["Temp"].fillna(moving_avg)
data["Temp"] = data["Temp"].round(0).astype("Int64")

In [311]:
data["DP"] = pd.to_numeric(data["DP"])
moving_avg = data["DP"].rolling(window=3, min_periods=1).mean()
data["DP"] = data["DP"].fillna(moving_avg)
data["DP"] = data["DP"].round(0).astype("Int64")

In [312]:
data.describe()

,Temp,DP,RH,Wind Speed,Pressure,Visibility
count,23084.0,23084.0,23084.000000,23084.000000,23084.0,22992.0
mean,27.311774,24.835081,87.467514,2.350806,1010.684024,8315.623956
std,2.940434,1.141984,12.412181,1.688946,2.215478,2398.400169
min,21.0,19.0,41.200000,0.000000,1004.0,300.0
25%,25.0,24.0,79.000000,1.000000,1009.0,7000.0
50%,26.0,25.0,94.100000,2.000000,1011.0,9999.0
75%,29.0,26.0,100.000000,3.000000,1012.0,9999.0
max,37.0,29.0,100.000000,18.000000,1018.0,9999.0

In [313]:
data.dtypes

Datetime       object
Temp            Int64
DP              Int64
RH            float64
Wind Speed      int64
Pressure        Int64
Visibility      Int64
Rain           object
dtype: object

## Label Encoding for Rain

In [314]:
print(data["Rain"].unique())

['NO' 'YES']

In [315]:
# Map "yes" → 1, "no" → 0
data["Rain"] = data["Rain"].map({"YES": 1, "NO": 0}).astype("int")

In [316]:
print(data["Rain"].unique())

[0 1]

In [317]:
data.describe()

,Temp,DP,RH,Wind Speed,Pressure,Visibility,Rain
count,23084.0,23084.0,23084.000000,23084.000000,23084.0,22992.0,23084.000000
mean,27.311774,24.835081,87.467514,2.350806,1010.684024,8315.623956,0.184370
std,2.940434,1.141984,12.412181,1.688946,2.215478,2398.400169,0.387794
min,21.0,19.0,41.200000,0.000000,1004.0,300.0,0.000000
25%,25.0,24.0,79.000000,1.000000,1009.0,7000.0,0.000000
50%,26.0,25.0,94.100000,2.000000,1011.0,9999.0,0.000000
75%,29.0,26.0,100.000000,3.000000,1012.0,9999.0,0.000000
max,37.0,29.0,100.000000,18.000000,1018.0,9999.0,1.000000

In [318]:
data.to_csv("FKKD_2021_to_2024_valid.csv", index=False)