In [54]:
import pandas as pd
import glob
import os

In [55]:
csv_folder = "processed_data/"  
output_file = "FKKD_2021_to_2024_processed.csv"

In [56]:
csv_files = sorted(glob.glob(os.path.join(csv_folder, "FKKD_202*.csv")))

In [57]:
for csv_file in csv_files :
    print(csv_file)

processed_data/FKKD_2021_Processed.csv
processed_data/FKKD_2022_Processed.csv
processed_data/FKKD_2023_Processed.csv
processed_data/FKKD_2024_Processed.csv

In [58]:
all_data = []

In [59]:
for csv_file in csv_files:
    df = pd.read_csv(csv_file)
    #df["SourceFile"] = os.path.basename(csv_file)  
    all_data.append(df)

In [60]:
combined_df = pd.concat(all_data, ignore_index=True)

In [61]:
combined_df.head()

,Unnamed: 0,Year,Month,Day,Hour,Temp,DP,RH,Wind Speed,Visibility,Rain,Pressure,Hour_int,Minute,Datetime
0,0,2021,1,1,0,26,26,100.0,0,7000.0,NO,1010.0,0,0,2021-01-01 00:00:00
1,1,2021,1,1,200,26,26,100.0,2,2500.0,NO,1009.0,2,0,2021-01-01 02:00:00
2,2,2021,1,1,300,25,25,100.0,2,6000.0,NO,NaN,3,0,2021-01-01 03:00:00
3,3,2021,1,1,400,25,25,100.0,0,6000.0,NO,1009.0,4,0,2021-01-01 04:00:00
4,4,2021,1,1,500,25,25,100.0,0,6000.0,NO,1010.0,5,0,2021-01-01 05:00:00

In [62]:
combined_df.tail()

,Unnamed: 0,Year,Month,Day,Hour,Temp,DP,RH,Wind Speed,Visibility,Rain,Pressure,Hour_int,Minute,Datetime
23083,8698,2024,12,31,100,27,26,94.3,0,8000.0,NO,1010.0,1,0,2024-12-31 01:00:00
23084,8699,2024,12,31,200,26,25,94.2,2,9999.0,NO,1009.0,2,0,2024-12-31 02:00:00
23085,8700,2024,12,31,300,26,25,94.2,1,9999.0,NO,1009.0,3,0,2024-12-31 03:00:00
23086,8701,2024,12,31,400,25,25,100.0,1,9999.0,NO,1009.0,4,0,2024-12-31 04:00:00
23087,8702,2024,12,31,800,29,25,79.0,2,4000.0,NO,1011.0,8,0,2024-12-31 08:00:00

In [63]:
combined_df.to_csv(output_file, index=False)